### ISSUE TITLE
Reusing button styling for a more complex element.

### ISSUE THREAD

**Issue by jalenmmorgan** [electrovir/vira#6]
Currently, there is no way to reuse the core button styling for more complicated button content. For example, what if I want a large image and several rows of bullet points of text?

One way this could be done is adding the equivalent of angular's `ng-content` to the button component. Another option is to export the css styling so it can be easily reused in a custom button component.

**Comment by electrovir** [comment]
`ViraButton` intentionally does not support non-plain-text children and there are no plans to change that.

> For example, what if I want a large image and several rows of bullet points of text?

Why should this ever be contained within a `ViraButton`? If it's simply meant to be a clickable, I'd think a native `<button>` would suffice?

> Another option is to export the css styling so it can be easily reused in a custom button component.

This is referring to more general color theming, which is definitely something that I want to add to Vira (but it's not present yet).

> equivalent of angular's `ng-content`

FYI that would be [`<slot>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/slot)
